name: WindowsMacBuild

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Cache MacOS nuitka build dependencies
        uses: actions/cache@v3
        env:
          cache-name: cache-nuitka
        id: cache-nuitka
        with:
          path: |
            /Users/runner/Library/Caches/Nuitka/downloads/ccache/
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create Python virtual environment
        run: |
          python -m venv venv

      - name: Build Mac OS
        run: |
          # source venv/bin/activate
          pip install imageio
          # pip install -r requirements.txt
          python ${{env.pythonLocation}}/lib/python3.10/site-packages/PySide6/scripts/deploy.py -c build/pysidedeploy_mac.spec --force --verbose

    #   - uses: actions/upload-artifact@v3
    #     with:
    #       name: renderrob_win
    #       path: |
    #         icons/
    #         ui/
    #         renderrob.exe

    #   - uses: actions/upload-artifact@v3
    #     with:
    #       name: renderrob_mac
    #       path: |
    #         icons/
    #         ui/
    #         renderrob.bin
    #         renderrob
